on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Verify commit exists in origin/master
      run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
        git branch --remote --contains | grep origin/master
    - name: Set VERSION variable from tag
      run: echo "VERSION=$($env:GITHUB_REF.replace('refs/tags/v', ''))" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
    - name: Restore packages
      run: dotnet restore
    - name: build
      run: dotnet build FilterDataGrid.Net5.0\FilterDataGrid.Net5.0.csproj --configuration Release /p:Version=${{ env.VERSION }}
    - name: pack
      run: dotnet pack FilterDataGrid.Net5.0\FilterDataGrid.Net5.0.csproj --configuration Release /p:Version=${{ env.VERSION }} --no-build
    - name: Push
      run: dotnet nuget push FilterDataGrid.Net5.0\bin\Release\*.nupkg --source https://nuget.pkg.github.com/ALTechUK/index.json --api-key ${{ env.GITHUB_TOKEN }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}